create user owndb password 'owndb_password' createdb;
create database own owner owndb;

create schema main authorization owndb;

select 1/0;

create table main.file_meta (
    id integer primary key generated by default as identity,
    file_data_id integer not null,
    extension char(32) not null,
    original_path text not null,
    size bigint not null,
    dt_created date not null,
    dt_changed date not null,
    foreign key (file_data_id) references main.file_data(id),
    constraint check_input check (
        extension != ''
        and original_path != ''
        and size > 0
    )
)
;

create table main.file_data (
    id integer primary key generated by default as identity,
    hash char(256) not null,
    data bytea not null, -- TODO: Fix the 1Gb data limit. See oid data type.
    constraint check_input check (
        length(hash) = 256
    )
)
;
